//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Control
{
    [Serializable]
    public class FollowJointTrajectoryActionMsg : Message
    {
        public const string k_RosMessageName = "control_msgs/FollowJointTrajectoryAction";
        public override string RosMessageName => k_RosMessageName;

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        public FollowJointTrajectoryActionGoalMsg action_goal;
        public FollowJointTrajectoryActionResultMsg action_result;
        public FollowJointTrajectoryActionFeedbackMsg action_feedback;

        public FollowJointTrajectoryActionMsg()
        {
            this.action_goal = new FollowJointTrajectoryActionGoalMsg();
            this.action_result = new FollowJointTrajectoryActionResultMsg();
            this.action_feedback = new FollowJointTrajectoryActionFeedbackMsg();
        }

        public FollowJointTrajectoryActionMsg(FollowJointTrajectoryActionGoalMsg action_goal, FollowJointTrajectoryActionResultMsg action_result, FollowJointTrajectoryActionFeedbackMsg action_feedback)
        {
            this.action_goal = action_goal;
            this.action_result = action_result;
            this.action_feedback = action_feedback;
        }

        public static FollowJointTrajectoryActionMsg Deserialize(MessageDeserializer deserializer) => new FollowJointTrajectoryActionMsg(deserializer);

        private FollowJointTrajectoryActionMsg(MessageDeserializer deserializer)
        {
            this.action_goal = FollowJointTrajectoryActionGoalMsg.Deserialize(deserializer);
            this.action_result = FollowJointTrajectoryActionResultMsg.Deserialize(deserializer);
            this.action_feedback = FollowJointTrajectoryActionFeedbackMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.action_goal);
            serializer.Write(this.action_result);
            serializer.Write(this.action_feedback);
        }

        public override string ToString()
        {
            return "FollowJointTrajectoryActionMsg: " +
            "\naction_goal: " + action_goal.ToString() +
            "\naction_result: " + action_result.ToString() +
            "\naction_feedback: " + action_feedback.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
