//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Control
{
    [Serializable]
    public class GripperCommandGoalMsg : Message
    {
        public const string k_RosMessageName = "control_msgs/GripperCommandGoal";
        public override string RosMessageName => k_RosMessageName;

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        public GripperCommandMsg command;

        public GripperCommandGoalMsg()
        {
            this.command = new GripperCommandMsg();
        }

        public GripperCommandGoalMsg(GripperCommandMsg command)
        {
            this.command = command;
        }

        public static GripperCommandGoalMsg Deserialize(MessageDeserializer deserializer) => new GripperCommandGoalMsg(deserializer);

        private GripperCommandGoalMsg(MessageDeserializer deserializer)
        {
            this.command = GripperCommandMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.command);
        }

        public override string ToString()
        {
            return "GripperCommandGoalMsg: " +
            "\ncommand: " + command.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
