//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Control
{
    [Serializable]
    public class JointTrajectoryActionMsg : Message
    {
        public const string k_RosMessageName = "control_msgs/JointTrajectoryAction";
        public override string RosMessageName => k_RosMessageName;

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        public JointTrajectoryActionGoalMsg action_goal;
        public JointTrajectoryActionResultMsg action_result;
        public JointTrajectoryActionFeedbackMsg action_feedback;

        public JointTrajectoryActionMsg()
        {
            this.action_goal = new JointTrajectoryActionGoalMsg();
            this.action_result = new JointTrajectoryActionResultMsg();
            this.action_feedback = new JointTrajectoryActionFeedbackMsg();
        }

        public JointTrajectoryActionMsg(JointTrajectoryActionGoalMsg action_goal, JointTrajectoryActionResultMsg action_result, JointTrajectoryActionFeedbackMsg action_feedback)
        {
            this.action_goal = action_goal;
            this.action_result = action_result;
            this.action_feedback = action_feedback;
        }

        public static JointTrajectoryActionMsg Deserialize(MessageDeserializer deserializer) => new JointTrajectoryActionMsg(deserializer);

        private JointTrajectoryActionMsg(MessageDeserializer deserializer)
        {
            this.action_goal = JointTrajectoryActionGoalMsg.Deserialize(deserializer);
            this.action_result = JointTrajectoryActionResultMsg.Deserialize(deserializer);
            this.action_feedback = JointTrajectoryActionFeedbackMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.action_goal);
            serializer.Write(this.action_result);
            serializer.Write(this.action_feedback);
        }

        public override string ToString()
        {
            return "JointTrajectoryActionMsg: " +
            "\naction_goal: " + action_goal.ToString() +
            "\naction_result: " + action_result.ToString() +
            "\naction_feedback: " + action_feedback.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
