//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Control
{
    [Serializable]
    public class PointHeadActionMsg : Message
    {
        public const string k_RosMessageName = "control_msgs/PointHeadAction";
        public override string RosMessageName => k_RosMessageName;

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        public PointHeadActionGoalMsg action_goal;
        public PointHeadActionResultMsg action_result;
        public PointHeadActionFeedbackMsg action_feedback;

        public PointHeadActionMsg()
        {
            this.action_goal = new PointHeadActionGoalMsg();
            this.action_result = new PointHeadActionResultMsg();
            this.action_feedback = new PointHeadActionFeedbackMsg();
        }

        public PointHeadActionMsg(PointHeadActionGoalMsg action_goal, PointHeadActionResultMsg action_result, PointHeadActionFeedbackMsg action_feedback)
        {
            this.action_goal = action_goal;
            this.action_result = action_result;
            this.action_feedback = action_feedback;
        }

        public static PointHeadActionMsg Deserialize(MessageDeserializer deserializer) => new PointHeadActionMsg(deserializer);

        private PointHeadActionMsg(MessageDeserializer deserializer)
        {
            this.action_goal = PointHeadActionGoalMsg.Deserialize(deserializer);
            this.action_result = PointHeadActionResultMsg.Deserialize(deserializer);
            this.action_feedback = PointHeadActionFeedbackMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.action_goal);
            serializer.Write(this.action_result);
            serializer.Write(this.action_feedback);
        }

        public override string ToString()
        {
            return "PointHeadActionMsg: " +
            "\naction_goal: " + action_goal.ToString() +
            "\naction_result: " + action_result.ToString() +
            "\naction_feedback: " + action_feedback.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
