//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Control
{
    [Serializable]
    public class SingleJointPositionActionResultMsg : Message
    {
        public const string k_RosMessageName = "control_msgs/SingleJointPositionActionResult";
        public override string RosMessageName => k_RosMessageName;

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        public HeaderMsg header;
        public Actionlib.GoalStatusMsg status;
        public SingleJointPositionResultMsg result;

        public SingleJointPositionActionResultMsg()
        {
            this.header = new HeaderMsg();
            this.status = new Actionlib.GoalStatusMsg();
            this.result = new SingleJointPositionResultMsg();
        }

        public SingleJointPositionActionResultMsg(HeaderMsg header, Actionlib.GoalStatusMsg status, SingleJointPositionResultMsg result)
        {
            this.header = header;
            this.status = status;
            this.result = result;
        }

        public static SingleJointPositionActionResultMsg Deserialize(MessageDeserializer deserializer) => new SingleJointPositionActionResultMsg(deserializer);

        private SingleJointPositionActionResultMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            this.status = Actionlib.GoalStatusMsg.Deserialize(deserializer);
            this.result = SingleJointPositionResultMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.status);
            serializer.Write(this.result);
        }

        public override string ToString()
        {
            return "SingleJointPositionActionResultMsg: " +
            "\nheader: " + header.ToString() +
            "\nstatus: " + status.ToString() +
            "\nresult: " + result.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
