//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Control
{
    [Serializable]
    public class GripperCommandActionMsg : Message
    {
        public const string k_RosMessageName = "control_msgs/GripperCommandAction";
        public override string RosMessageName => k_RosMessageName;

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        public GripperCommandActionGoalMsg action_goal;
        public GripperCommandActionResultMsg action_result;
        public GripperCommandActionFeedbackMsg action_feedback;

        public GripperCommandActionMsg()
        {
            this.action_goal = new GripperCommandActionGoalMsg();
            this.action_result = new GripperCommandActionResultMsg();
            this.action_feedback = new GripperCommandActionFeedbackMsg();
        }

        public GripperCommandActionMsg(GripperCommandActionGoalMsg action_goal, GripperCommandActionResultMsg action_result, GripperCommandActionFeedbackMsg action_feedback)
        {
            this.action_goal = action_goal;
            this.action_result = action_result;
            this.action_feedback = action_feedback;
        }

        public static GripperCommandActionMsg Deserialize(MessageDeserializer deserializer) => new GripperCommandActionMsg(deserializer);

        private GripperCommandActionMsg(MessageDeserializer deserializer)
        {
            this.action_goal = GripperCommandActionGoalMsg.Deserialize(deserializer);
            this.action_result = GripperCommandActionResultMsg.Deserialize(deserializer);
            this.action_feedback = GripperCommandActionFeedbackMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.action_goal);
            serializer.Write(this.action_result);
            serializer.Write(this.action_feedback);
        }

        public override string ToString()
        {
            return "GripperCommandActionMsg: " +
            "\naction_goal: " + action_goal.ToString() +
            "\naction_result: " + action_result.ToString() +
            "\naction_feedback: " + action_feedback.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
