//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Control
{
    [Serializable]
    public class JointTrajectoryGoalMsg : Message
    {
        public const string k_RosMessageName = "control_msgs/JointTrajectoryGoal";
        public override string RosMessageName => k_RosMessageName;

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        public Trajectory.JointTrajectoryMsg trajectory;

        public JointTrajectoryGoalMsg()
        {
            this.trajectory = new Trajectory.JointTrajectoryMsg();
        }

        public JointTrajectoryGoalMsg(Trajectory.JointTrajectoryMsg trajectory)
        {
            this.trajectory = trajectory;
        }

        public static JointTrajectoryGoalMsg Deserialize(MessageDeserializer deserializer) => new JointTrajectoryGoalMsg(deserializer);

        private JointTrajectoryGoalMsg(MessageDeserializer deserializer)
        {
            this.trajectory = Trajectory.JointTrajectoryMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.trajectory);
        }

        public override string ToString()
        {
            return "JointTrajectoryGoalMsg: " +
            "\ntrajectory: " + trajectory.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
