//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Control
{
    [Serializable]
    public class PointHeadFeedbackMsg : Message
    {
        public const string k_RosMessageName = "control_msgs/PointHeadFeedback";
        public override string RosMessageName => k_RosMessageName;

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        public double pointing_angle_error;

        public PointHeadFeedbackMsg()
        {
            this.pointing_angle_error = 0.0;
        }

        public PointHeadFeedbackMsg(double pointing_angle_error)
        {
            this.pointing_angle_error = pointing_angle_error;
        }

        public static PointHeadFeedbackMsg Deserialize(MessageDeserializer deserializer) => new PointHeadFeedbackMsg(deserializer);

        private PointHeadFeedbackMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.pointing_angle_error);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pointing_angle_error);
        }

        public override string ToString()
        {
            return "PointHeadFeedbackMsg: " +
            "\npointing_angle_error: " + pointing_angle_error.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
