//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Control
{
    [Serializable]
    public class SingleJointPositionActionMsg : Message
    {
        public const string k_RosMessageName = "control_msgs/SingleJointPositionAction";
        public override string RosMessageName => k_RosMessageName;

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        public SingleJointPositionActionGoalMsg action_goal;
        public SingleJointPositionActionResultMsg action_result;
        public SingleJointPositionActionFeedbackMsg action_feedback;

        public SingleJointPositionActionMsg()
        {
            this.action_goal = new SingleJointPositionActionGoalMsg();
            this.action_result = new SingleJointPositionActionResultMsg();
            this.action_feedback = new SingleJointPositionActionFeedbackMsg();
        }

        public SingleJointPositionActionMsg(SingleJointPositionActionGoalMsg action_goal, SingleJointPositionActionResultMsg action_result, SingleJointPositionActionFeedbackMsg action_feedback)
        {
            this.action_goal = action_goal;
            this.action_result = action_result;
            this.action_feedback = action_feedback;
        }

        public static SingleJointPositionActionMsg Deserialize(MessageDeserializer deserializer) => new SingleJointPositionActionMsg(deserializer);

        private SingleJointPositionActionMsg(MessageDeserializer deserializer)
        {
            this.action_goal = SingleJointPositionActionGoalMsg.Deserialize(deserializer);
            this.action_result = SingleJointPositionActionResultMsg.Deserialize(deserializer);
            this.action_feedback = SingleJointPositionActionFeedbackMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.action_goal);
            serializer.Write(this.action_result);
            serializer.Write(this.action_feedback);
        }

        public override string ToString()
        {
            return "SingleJointPositionActionMsg: " +
            "\naction_goal: " + action_goal.ToString() +
            "\naction_result: " + action_result.ToString() +
            "\naction_feedback: " + action_feedback.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
