//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.BuiltinInterfaces;

namespace RosMessageTypes.Control
{
    [Serializable]
    public class SingleJointPositionGoalMsg : Message
    {
        public const string k_RosMessageName = "control_msgs/SingleJointPositionGoal";
        public override string RosMessageName => k_RosMessageName;

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        public double position;
        public DurationMsg min_duration;
        public double max_velocity;

        public SingleJointPositionGoalMsg()
        {
            this.position = 0.0;
            this.min_duration = new DurationMsg();
            this.max_velocity = 0.0;
        }

        public SingleJointPositionGoalMsg(double position, DurationMsg min_duration, double max_velocity)
        {
            this.position = position;
            this.min_duration = min_duration;
            this.max_velocity = max_velocity;
        }

        public static SingleJointPositionGoalMsg Deserialize(MessageDeserializer deserializer) => new SingleJointPositionGoalMsg(deserializer);

        private SingleJointPositionGoalMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.position);
            this.min_duration = DurationMsg.Deserialize(deserializer);
            deserializer.Read(out this.max_velocity);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.position);
            serializer.Write(this.min_duration);
            serializer.Write(this.max_velocity);
        }

        public override string ToString()
        {
            return "SingleJointPositionGoalMsg: " +
            "\nposition: " + position.ToString() +
            "\nmin_duration: " + min_duration.ToString() +
            "\nmax_velocity: " + max_velocity.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
